_target_: src.datamodules.hyperdist_datamodule.HYPERDISTDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
seed: 777  # dataset generation seed
n_samples: 1.0e+5  # it will be divided in 70:20:10 ratio
dim: 2
curv: 1
inverse_transform: hyperbolic
min_r: 0.1
max_r: 5.3
batch_size: 256
num_workers: 1
pin_memory: False
